# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cosmic-inference-demo',
                'doc_host': 'https://berianjames.github.io',
                'git_url': 'https://github.com/berianjames/cosmic-inference-demo',
                'lib_path': 'cosmic_inference_demo'},
  'syms': {'cosmic_inference_demo.core': {'cosmic_inference_demo.core.foo': ('core.html#foo', 'cosmic_inference_demo/core.py')}}}
